### ISSUE TITLE
make testbin -C arch/lib/test don't work

### ISSUE THREAD

**Issue by Joilnen** [direct-code-execution/net-next-sim#3]
CC       sim.o
  LINK     libsim-linux-4.0.0.so
make[2]: `librumpclient.so' está atualizado.
make[2]:`libnuse-hijack.so' está atualizado.
compe@TankBox:~/dce/net-next-sim$ make testbin -C arch/lib/test
make: **\* arch/lib/test: Arquivo ou diretório não encontrado.  Pare.

**Comment by thehajime** [comment]
Try make testbin -C tools/testing/libos instead.
